#  menu items
# [[main]]
#   name = "Blog"
#   weight = 5
#   url = "blog/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

# [[main]]
#   name = "Tutorials"
#   weight = 2
#   url = "tutorials/"

[[main]]
  name = "Status"
  weight = 3
  url = "https://status.draupnir.midnightthoughts.space/"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"